ecom_app/urls.py
from django.urls import path
from . import views

app_name='ecom_app'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('login/',views.userLogin,name='userLogin'),
    path('register/',views.register,name='register'),
    path('logout/',views.userLogout,name='userLogout'),


    # api section----------------------------------------------
    path('updateItem/', views.updateItem, name='updateItem'),
    path('process_order/', views.process_order, name='process_order')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name=models.CharField(max_length=254, null=True)
    email=models.EmailField(max_length=254, null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=254)
    price=models.FloatField(null=True)
    digital=models.BooleanField(default=False, null=True, blank=True)
    image=models.ImageField(upload_to='product_pics', null=True)
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url

class Order(models.Model):
    customer=models.ForeignKey(Customer,null=True, blank=True, on_delete=models.CASCADE)
    date_order=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=100, null=True)
    def __str__(self):
        return f'{str(self.id)}---{self.customer.name}'

    @property
    def total_cart_items(self):
        order_items=self.orderitem_set.all()
        total=0
        for item in order_items:
            total+=item.quantity
        return total

    @property
    def total_cart_amount(self):
        order_items=self.orderitem_set.all()
        total=0
        for item in order_items:
            total+=item.get_total
        return total
    @property
    def shipping(self):
        shipping=False
        order_items=self.orderitem_set.all()
        for item in order_items:
            if item.product.digital == False:
                shipping=True
        return shipping


class OrderItem(models.Model):
    product=models.ForeignKey(Product,null=True, blank=True, on_delete=models.CASCADE)
    order=models.ForeignKey(Order,null=True, blank=True, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0, null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        # return self.product.name
        return f'{self.product.name}---order{self.order.id}'

    @property
    def get_total(self):
        total=(self.product.price*self.quantity)
        return total

class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer,null=True, blank=True, on_delete=models.SET_NULL)
    order=models.ForeignKey(Order,null=True, blank=True, on_delete=models.SET_NULL)
    address=models.CharField(max_length=254, null=False)
    city=models.CharField(max_length=254, null=False)
    state=models.CharField(max_length=254, null=False)
    zip_code=models.CharField(max_length=254, null=False)
    country=models.CharField(max_length=254, null=False)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.address

ecom_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class CreateUserForm(UserCreationForm):
    username=forms.CharField(widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter Your UserName'
            }
        ))
    email=forms.EmailField(widget=forms.EmailInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter Your Email'
            }
        ))
    password1=forms.CharField(widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter Your Password'
            }
        ))
    password2=forms.CharField(widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'Re-Enter Your Password'
            }
        ))
    class Meta:
        model=User
        fields=['username','email','password1','password2']

ecom_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
import datetime
import json
from .utils import cookieCart, cartData, guestOrder
from .forms import CreateUserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.
def store(request):
    # products=Product.objects.all()
    # products=Paginator(products,6)
    # context={'products':products}
    # return render(request,'ecom_app/store.html',context)

    data=cartData(request)
    cart_items=data['cart_items']

    products=Product.objects.all()
    paginator=Paginator(products,3)

    page_number=request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context={'page_obj':page_obj, 'cart_items':cart_items}
    return render(request,'ecom_app/store.html',context)

def cart(request):
    data=cartData(request)
    cart_items=data['cart_items']
    order=data['order']
    items=data['items']

    context={'items':items, 'order':order, 'cart_items':cart_items}
    return render(request,'ecom_app/cart.html',context)

def checkout(request):
    data=cartData(request)
    cart_items=data['cart_items']
    order=data['order']
    items=data['items']

    context={'items':items, 'order':order, 'cart_items':cart_items}
    return render(request,'ecom_app/checkout.html',context)

def updateItem(request):
    product_id=request.POST.get('product_id')
    product_action=request.POST.get('product_action')
    customer=request.user.customer
    product=Product.objects.get(id=product_id)
    order, created=Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created=OrderItem.objects.get_or_create(order=order, product=product)

    if product_action=='add':
        orderItem.quantity+=1
    else:
        orderItem.quantity-=1
    orderItem.save()
    if orderItem.quantity <=0:
        orderItem.delete()

    cart_count=order.total_cart_items

    return JsonResponse({'success':'Product added Successfully!!!','order_id':order.id,'cart_count':cart_count,'shipping':False})

def process_order(request):
    address=request.POST.get('address')
    city=request.POST.get('city')
    state=request.POST.get('state')
    zip_code=request.POST.get('zip_code')
    country=request.POST.get('country')
    total_amount=float(request.POST.get('total_amount'))
    # example of dynamic transaction_id
    transaction_id=datetime.datetime.now().timestamp()


    if request.user.is_authenticated:
        customer=request.user.customer
        order,created=Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer,order=guestOrder(request)

    order.transaction_id=transaction_id
    if total_amount == order.total_cart_amount:
        order.complete=True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(customer=customer,order=order,
                                    address=address,city=city,state=state,
                                    zip_code=zip_code,country=country)

    return JsonResponse({'success':'Order Placed Successfully!!!'})

def userLogin(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('ecom_app:store')
        else:
            messages.info(request, 'Invalid UserName or Password!!')
            return redirect('ecom_app:userLogin')

    return render(request,'ecom_app/login.html')

def userLogout(request):
    logout(request)
    return redirect('ecom_app:store')

def register(request):
    form=CreateUserForm()
    if request.method == 'POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            user_name=form.cleaned_data.get('username')
            form.save()
            cus_user=User.objects.get(username=user_name)
            Customer.objects.create(user=cus_user,name=cus_user,email=cus_user.email)
            messages.success(request, 'New Account was created named: '+user_name)
            return redirect('ecom_app:userLogin')


    context={'form':form}
    return render(request,'ecom_app/register.html',context)

ecom_app/templates/ecom_app/cart.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block title_block %}
  Store
{% endblock %}

{% block body_block %}
  <div class="row">

    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <a href="{% url 'ecom_app:store' %}" class="btn btn-outline-dark">&#8592;Continue Shopping</a>
          <table class="table">
            <tr>
              <th>Items:<strong>{{ order.total_cart_items }}</strong></th>
              <th>Totla:<strong>${{ order.total_cart_amount|floatformat:2 }}</strong></th>
              <th>
                <a href="{% url 'ecom_app:checkout' %}" class="btn btn-success" style="float:right;">Checkout</a>
              </th>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table">
            <tr>
              <td><h6></h6></td>
              <td><h6>Items</h6></td>
              <td><h6>Price</h6></td>
              <td><h6>Quantity</h6></td>
              <td><h6>Total</h6></td>
            </tr>

            {% for item in items %}
              <tr>
                <td><img src="{{ item.product.imageURL }}" alt="" class="cart_page_img"></td>
                <td><h6>{{ item.product.name }}</h6></td>
                <td><h6>${{ item.product.price }}</h6></td>
                <td>
                  <h6 style="display:inline-block;">{{ item.quantity }}</h6>
                  <div style="display:inline-block;">
                    <img src="{% static 'images/up.png' %}" alt="" class="arrow_icon update-cart" style="margin-bottom:3px;" data-product="{{ item.product.id }}" data-action="add">
                    <img src="{% static 'images/down.png' %}" alt="" class="arrow_icon update-cart" data-product="{{ item.product.id }}" data-action="remove">
                  </div>
                </td>
                <td><h6>${{ item.get_total|floatformat:2 }}</h6></td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

ecom_app/templates/ecom_app/checkout.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block title_block %}
  Checkout
{% endblock %}

{% block body_block %}
  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <div class="" id="total_info">
            <form class=""  method="post" id="shipping_form">
              <!-- user info section -->
              <div class="row" id="user_info">
                <div class="form-group col-lg-6">
                   <input type="text" class="form-control" name="user_name" placeholder="Name">
                 </div>
                 <div class="form-group col-lg-6">
                    <input type="email" class="form-control" name="user_email" aria-describedby="emailHelp" placeholder="Email">
                 </div>
              </div>
              <div class="" id="shipping_info_head">
                <hr>
                <p>Shipping Information</p>
                <hr>
              </div>

              <!-- shipping info section -->
              <div class="row" id="shipping_info">
                <div class="form-group col-lg-6">
                   <input type="text" class="form-control" name="address" placeholder="Address..">
                 </div>
                 <div class="form-group col-lg-6">
                    <input type="text" class="form-control" name="city" placeholder="City..">
                 </div>
                 <div class="form-group col-lg-6">
                    <input type="text" class="form-control" name="state" placeholder="State..">
                  </div>
                  <div class="form-group col-lg-6">
                     <input type="text" class="form-control" name="zip_code" placeholder="Zip Code..">
                  </div>
                  <div class="form-group col-lg-6">
                     <input type="text" class="form-control" name="country" placeholder="Country..">
                  </div>
              </div>
              <input type="submit" value="Continue" class="btn btn-success btn-block" id="ship_form_btn">
            </form>
          </div>
          <!-- paypal option start -->
          <div id="payment_info">
            <hr>
            <span>Paypal Option</span>
            <hr>
            <!-- Set up a container element for the button -->
            <div id="paypal-button-container"></div>
            <!-- <button type="button" class="btn btn-outline-danger" id="make_payment" style="float:right;" >Make Payment</button> -->
            <hr>

          </div>

        </div>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
            <a href="{% url 'ecom_app:cart' %}" class="btn btn-outline-dark">&#8592;Back to Cart</a>
            <hr>
            <h5>Order Summery..</h5>
            <table class="table">
              {% for item in items %}
                <tr>
                  <td><img src="{{ item.product.imageURL }}" alt="" class="cart_page_img"></td>
                  <td><h6>{{ item.product.name }}</h6></td>
                  <td><h6>${{ item.product.price }}</h6></td>
                  <td><h6>x{{ item.quantity }}</h6></td>
                </tr>
              {% endfor %}
            </table>
            <h5>Items: {{ order.total_cart_items }}</h5>
            <h5>Total: ${{ order.total_cart_amount|floatformat:2 }}</h5>
        </div>
      </div>
    </div>

  </div>


{% endblock %}

{% block script_block %}

  <script src="https://www.paypal.com/sdk/js?client-id=AfDIpZJbrN9BVPGC0gGNIjE0t16-_DkjAnVguf9No3k1QrOXqWLgGmRiEYKPgWD_5JE-4gNi21tUZct1&currency=USD&disable-funding=credit"></script>
  <script>
    var total_amount='{{ order.total_cart_amount }}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({
      style:{
        color:'blue',
        shape:'rect'
      },

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total_amount).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                submitFormData()
            });
        }


    }).render('#paypal-button-container');
</script>

  <script type="text/javascript">
    var shipping='{{ order.shipping }}'
    if(shipping=='False')
    {
      $('#shipping_info').hide()
      $('#shipping_info_head').hide()
    }
    if(user !='AnonymousUser')
    {
      $('#user_info').hide()
    }
    if(user !='AnonymousUser' && shipping=='False')
    {
      $('#total_info').hide()
      $('#payment_info').show()
    }


    $('#shipping_form').submit(function(e){
      e.preventDefault();
      $('#ship_form_btn').hide()
      $('#payment_info').show()
    });

    function submitFormData()
    {
      $.ajax({
        headers: {
            'X-CSRFToken':csrftoken
        },
        url:'/process_order/',
        type:'POST',
        data:$('#shipping_form').serialize()+ "&total_amount=" + total_amount,
        success:function(data){
          alert('Your Transection is completed!!!')
          deleteCookie('cart')
          localStorage.cart_count=0
          window.location.href="{% url 'ecom_app:store' %}"

        }
      });
    }


  </script>
{% endblock %}

ecom_app/templates/ecom_app/login.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block title_block %}
  Login
{% endblock %}

{% block css_block %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body_block %}
  <div class="wrapper fadeInDown">
    <div id="formContent">
      <form method="POST">
        {% csrf_token %}
        <br>
        <input type="text" class="fadeIn second" name="username" placeholder="Enter Your UserName">
        <input type="password" class="fadeIn third" name="password" placeholder="Enter Your Password">
        <input type="submit" class="fadeIn fourth" value="Log In">
      </form>

      <!-- Remind Passowrd -->
      <div id="formFooter">
        <span>Don't have account? </span><a class="underlineHover" href="{% url 'ecom_app:register' %}">Please Register</a>
      </div>

    </div>
  </div>
{% endblock %}

{% block script_block %}
  <script type="text/javascript">
    $('#cart_total').hide()
    $('#cart_icon').hide()
  </script>
{% endblock %}

ecom_app/templates/ecom_app/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title_block %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css_block %}
    {% endblock %}
    <script type="text/javascript">

        var user='{{ request.user }}';
        // set cookies funation
        function setCookie(cname, cvalue, exdays) {
          cvalue=JSON.stringify(cvalue);
          var d = new Date();
          d.setTime(d.getTime() + (exdays*24*60*60*1000));
          var expires = "expires="+ d.toUTCString();
          document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
        }
        // get cookies funation
        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
        // delete COOKIES
        function deleteCookie(name) { setCookie(name, '', -1); }

        const csrftoken = getCookie('csrftoken');

        var cart=JSON.parse(getCookie('cart'))

        if(cart == undefined)
        {
          cart={};
          setCookie('cart', cart, 3)
        }
        // console.log("cart:",cart)
    </script>
  </head>

  <body>
    {% include "ecom_app/navbar.html" %}
    <div class="container">
      <br>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          {% if messages %}
            {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }}" role="alert">
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}
            </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="col-md-3"></div>
      </div>

      {% block body_block %}
        <!-- body section -->
      {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    <script type="text/javascript">

      // if (localStorage.getItem("cart_count") == null) {
      //     $('#cart_total').text(0)
      // }
      // else{
      //   $('#cart_total').text(localStorage.getItem('cart_count'))
      // }

      if (user =='AnonymousUser')
      {
        // alert('AnonymousUser')
        // localStorage.cart_count = 0;
        // if (localStorage.getItem("cart_count") == null) {
        //     $('#cart_total').text(0)
        // }
        // else{
        //   $('#cart_total').text(localStorage.getItem('cart_count'))
        // }
      }
      // else{
      //   $('#cart_total').text(localStorage.getItem('cart_count'))
      // }


      // $('#cart_total').text(localStorage.getItem('cart_count'))


      // console.log(localStorage.getItem('cart_count'))
    </script>

    {% block script_block %}
    {% endblock %}
  </body>
</html>

ecom_app/templates/ecom_app/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'ecom_app:store' %}">NK.com</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecom_app:store' %}">Store <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      {% if user.is_authenticated %}
        <a href="{% url 'ecom_app:userLogout' %}" class="btn btn-success">Logout</a>
      {% else %}
        <a href="{% url 'ecom_app:userLogin' %}" class="btn btn-success">Login</a>
      {% endif %}
      <a href="{% url 'ecom_app:cart' %}" >
        <img src="{% static 'images/cart.jpg' %}" alt="" id="cart_icon">
      </a>
      <p id="cart_total">{{ cart_items }}</p>
    </div>
  </div>
</nav>

ecom_app/templates/ecom_app/register.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block title_block %}
  Register
{% endblock %}

{% block body_block %}
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          Register Yourself!!!
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            <!-- validation section start -->
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <span>{{ error|escape }}</span>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in new_form.non_field_errors %}
                    <div class="alert alert-danger">
                        <span>{{ error|escape }}</span>
                    </div>
                {% endfor %}
            {% endif %}
            <!-- validation section end -->
            <div class="form-group">
              <label>UserName</label>
              {{ form.username }}
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              {{ form.email }}
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              {{ form.password1 }}
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Confirm Password</label>
              {{ form.password2 }}
            </div>
            <button type="submit" class="btn btn-success">Register</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-lg-3"></div>
  </div>
{% endblock %}

{% block script_block %}
  <script type="text/javascript">
    $('#cart_total').hide()
    $('#cart_icon').hide()
  </script>
{% endblock %}

ecom_app/templates/ecom_app/store.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block title_block %}
  Store
{% endblock %}

{% block body_block %}
  <div class="row">
    {% for product in page_obj %}
      <div class="col-lg-4">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="{{  product.imageURL }}" alt="Card image cap" style="height:13rem;">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <hr>
            <button type="button" data-product="{{ product.id }}" data-action="add" name="button" class="btn btn-outline-secondary update-cart">Add to Cart</button>
            <a href="#" class="btn btn-outline-success">View</a>
            <p style="float:right;margin-bottom:0rem;">${{ product.price|floatformat:2 }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>


  <!-- pagination section start -->

  <div class="text-center">
    <br>
    {% if page_obj.has_previous %}
      <a href="?page=1" class="btn btn-outline-info mb-2">First</a>
      <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-2">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
         <a href="?page={{ num }}" class="btn btn-info mb-2">{{ num }}</a>
       {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
         <a href="?page={{ num }}" class="btn btn-outline-info mb-2">{{ num }}</a>
       {% endif %}
     {% endfor %}

     {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-2">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-2">Last</a>
     {% endif %}
  </div>

  <!-- pagination section end -->

{% endblock %}